const songs = [
  {
    name: "Apocalypse",
    path: "/assets/musics/Song1.mp3",
    duration: "03 : 09",
    artist: "Midranger",
    cover: "assets/images/cover1.png",
    year: 2020,
  },
  {
    name: "On & on",
    path: "/assets/musics/Song2.mp3",
    duration: "03 : 28",
    artist: "Daniel Levi",
    cover: "assets/images/cover2.png",
    year: 2015,
  },
  {
    name: "sv - Dogle",
    path: "/assets/musics/Song3.mp3",
    duration: "02 : 20",
    artist: "Sv -The Poet",
    cover: "assets/images/cover3.png",
    year: 2022,
  },
  {
    name: "Island - MBB",
    path: "/assets/musics/Song4.mp3",
    duration: "02 : 04",
    artist: "MBB",
    cover: "assets/images/cover4.png",
    year: 2017,
  },
  {
    name: "Like me",
    path: "/assets/musics/Song5.mp3",
    duration: "03 : 32",
    artist: "T-Mass & Britt Lari",
    cover: "assets/images/cover5.png",
    year: 2020,
  },
  {
    name: "Happy",
    path: "/assets/musics/Song6.mp3",
    duration: "03 : 06",
    artist: "Make Leite",
    cover: "assets/images/cover6.png",
    year: 2020,
  },
  {
    name: "Warriyo Mortals",
    path: "/assets/musics/Song7.mp3",
    duration: "03 : 48",
    artist: "Warriyo",
    cover: "assets/images/cover7.png",
    year: 2016,
  },
  {
    name: "safe & sound",
    path: "/assets/musics/Song8.mp3",
    duration: "03 : 29",
    artist: "Deaf Kev",
    cover: "assets/images/cover8.png",
    year: 2020,
  },
];
export default songs;
